//==================================================================================================
/// \file
/// This header-file is part of the \aliblong.
///
/// Copyright 2013-2026 A-Worx GmbH, Germany.
/// Published under #"mainpage_license".
//==================================================================================================
#ifndef H_ALIB_BOXING_STDBOXTRAITS
#define H_ALIB_BOXING_STDBOXTRAITS
#pragma once
#ifndef HPP_ALIB
#   include "alib/alib.prepro.hpp"
#endif

#if ALIB_BOXING
//=========================================== Dependencies =========================================
#include "ALib.Boxing.H"
#include "ALib.Strings.H"

//============================================= Includes ===========================================
#include "alib/boxing/stdboxtraits.hpp"

#endif // ALIB_BOXING
#endif // H_ALIB_BOXING_STDBOXTRAITS
