//==================================================================================================
/// \file
/// This header-file is part of the \aliblong.
///
/// Copyright 2013-2026 A-Worx GmbH, Germany.
/// Published under #"mainpage_license".
//==================================================================================================
#ifndef H_ALIB_FORMAT_FORMATTERPYTHONSTYLE
#define H_ALIB_FORMAT_FORMATTERPYTHONSTYLE
#pragma once
#ifndef HPP_ALIB
#   include "alib/alib.prepro.hpp"
#endif

#if ALIB_FORMAT
//=========================================== Dependencies =========================================
#include "ALib.Boxing.H"
#include "ALib.Strings.AutoSizes.H"
#include "ALib.Format.H"
#include "ALib.Format.StdImplementation.H"

//============================================= Imports ============================================
#if ALIB_C20_MODULES
import ALib.Format.FormatterPythonStyle;
#else
#include "alib/format/formatterpythonstyle.hpp"

#endif // ALIB_C20_MODULES
#endif // ALIB_FORMAT
#endif // H_ALIB_FORMAT_FORMATTERPYTHONSTYLE
