//==================================================================================================
/// \file
/// This header-file is part of the \aliblong.
///
/// \emoji :copyright: 2013-2025 A-Worx GmbH, Germany.
/// Published under \ref mainpage_license "Boost Software License".
//==================================================================================================
#ifndef H_ALIB_FORMAT_PARAGRAPHS
#define H_ALIB_FORMAT_PARAGRAPHS
#pragma once
#ifndef INL_ALIB
#   include "alib/alib.inl"
#endif

#if ALIB_FORMAT
#   if ALIB_C20_MODULES && !DOXYGEN
        import ALib.Format.Paragraphs;
#   elif !defined(ALIB_INC_FORMAT_PARAGRAPHS_MPP)
#       define ALIB_INC_FORMAT_PARAGRAPHS_MPP
#       include "alib/format/paragraphs.mpp"
#   endif
#endif

#endif // H_ALIB_FORMAT_PARAGRAPHS

