//==================================================================================================
/// \file
/// This header-file is part of the \aliblong.
///
/// Copyright 2013-2026 A-Worx GmbH, Germany.
/// Published under #"mainpage_license".
//==================================================================================================
#ifndef H_ALIB_BOXING_STDFUNCTORS
#define H_ALIB_BOXING_STDFUNCTORS
#pragma once
#ifndef HPP_ALIB
#   include "alib/alib.prepro.hpp"
#endif

#if ALIB_BOXING
//=========================================== Dependencies =========================================
#include "ALib.Boxing.H"

//============================================= Imports ============================================
#if ALIB_C20_MODULES
import ALib.Boxing.StdFunctors;
#else
#include "alib/boxing/stdfunctors.hpp"

#endif // ALIB_C20_MODULES
#endif // ALIB_BOXING
#endif // H_ALIB_BOXING_STDFUNCTORS
