//==================================================================================================
/// \file
/// This header-file is part of the \aliblong.
///
/// \emoji :copyright: 2013-2025 A-Worx GmbH, Germany.
/// Published under \ref mainpage_license "Boost Software License".
//==================================================================================================
#ifndef H_ALIB_LANG
#define H_ALIB_LANG
#pragma once
#ifndef INL_ALIB
#   include "alib/alib.inl"
#endif

#if ALIB_C20_MODULES && !DOXYGEN
    import ALib.Lang;
#elif !defined(ALIB_INC_LANG_MPP)
#   define ALIB_INC_LANG_MPP
#   include "alib/lang/lang.mpp"
#endif

#endif // H_ALIB_LANG

