//==================================================================================================
/// \file
/// This header-file is part of the \aliblong.
///
/// \emoji :copyright: 2013-2025 A-Worx GmbH, Germany.
/// Published under \ref mainpage_license "Boost Software License".
//==================================================================================================
#ifndef H_ALIB_CHARACTERS_FUNCTIONS
#define H_ALIB_CHARACTERS_FUNCTIONS
#pragma once
#ifndef INL_ALIB
#   include "alib/alib.inl"
#endif

#if ALIB_C20_MODULES && !DOXYGEN
    import ALib.Characters.Functions;
#elif !defined(ALIB_INC_CHARACTERS_FUNCTIONS_MPP)
#   define ALIB_INC_CHARACTERS_FUNCTIONS_MPP
#   include "alib/characters/functions.mpp"
#endif

#endif // H_ALIB_CHARACTERS_FUNCTIONS

