//==================================================================================================
/// \file
/// This header-file is part of the \aliblong.
///
/// Copyright 2013-2026 A-Worx GmbH, Germany.
/// Published under #"mainpage_license".
//==================================================================================================
#ifndef H_ALIB_CHARACTERS_FUNCTIONS
#define H_ALIB_CHARACTERS_FUNCTIONS
#pragma once
#ifndef HPP_ALIB
#   include "alib/alib.prepro.hpp"
#endif

//=========================================== Dependencies =========================================
#include "ALib.Lang.H"
#include <cstring>

//============================================= Imports ============================================
#if ALIB_C20_MODULES
import ALib.Characters.Functions;
#else
#include "alib/characters/functions.hpp"
#endif // ALIB_C20_MODULES
#endif // H_ALIB_CHARACTERS_FUNCTIONS
